### ISSUE TITLE
Running this code on my own servers "something went wrong" each time.

### ISSUE THREAD

**Issue by pnunn** [ibrahima92/apollo-graphql-full-stack#2]
Hi, 

I know this is an absolute beginners question, but how does the client app know where to find the server?  I'm running the server in one terminal and its listening on localhost:4000, and running the client in another terminal and its showing localhost:3000 but I can't for the life of me work out how they find each other. When I start the client I get "Something went wrong!" constantly and I'm guessing its because the client can't find the server?

**Comment by ibrahima92** [comment]
In the `index.js` file, we imported `ApolloClient` which is responsible to connect the server with the client-side app. To change the server address, just update the value of the `uri` property.
```jsx
const client = new ApolloClient({
  uri: 'https://7sgx4.sse.codesandbox.io' // change that vakue
})
```

**Comment by pnunn** [comment]
Thanks @ibrahima92.. got it working...
For those following along at home... I needed to set the server to listen(4000,'0.0.0.0') and the client uri to be '192.168.44.147:4000' and all started working (pretty much everything else gave me connection refused in the network tab of the chrome dev tools.

Thanks for putting this together.. very useful. Now to start digging :)
P.
